
(function () {
var scripts = [{"deps":{"./assets/enums/MachineType":1,"./assets/enums/PlantType":12,"./assets/enums/Type":17,"./assets/enums/WorkerType":23,"./assets/enums/YieldType":11,"./assets/enums/CattleType":18,"./assets/interfaces/ILand":4,"./assets/interfaces/IMachine":22,"./assets/interfaces/IStorage":15,"./assets/interfaces/IStore":16,"./assets/interfaces/IWorker":24,"./assets/interfaces/IYield":27,"./assets/interfaces/IAsset":21,"./assets/scripts/Manager/GameSaveManager":36,"./assets/scripts/Manager/UIManager":35,"./assets/scripts/Manager/ConfigManager":3,"./assets/scripts/PanelUI":37,"./assets/scripts/Store/Store":5,"./assets/scripts/controllers/GameController":6,"./assets/scripts/data/GameConfig":7,"./assets/scripts/models/GameModel":8,"./assets/scripts/models/LandModel":30,"./assets/scripts/models/MachineModel":26,"./assets/scripts/models/PlantModel":25,"./assets/scripts/models/WorkerModel":29,"./assets/scripts/models/YieldModel":32,"./assets/scripts/models/CattleModel":28,"./assets/scripts/storage/Storage":9,"./assets/scripts/ui/StorageUI":10,"./assets/scripts/ui/StoreUI":34,"./assets/scripts/ui/LandUI":33,"./assets/scripts/utils/CSVLoader":13,"./assets/scripts/views/GameView":14,"./assets/core/mvc/BaseView":2,"./assets/core/mvc/BaseController":19,"./assets/core/mvc/BaseModel":20,"./assets/enums/LandType":31},"path":"preview-scripts/__qc_index__.js"},{"deps":{},"path":"preview-scripts/assets/enums/MachineType.js"},{"deps":{},"path":"preview-scripts/assets/core/mvc/BaseView.js"},{"deps":{},"path":"preview-scripts/assets/scripts/Manager/ConfigManager.js"},{"deps":{},"path":"preview-scripts/assets/interfaces/ILand.js"},{"deps":{},"path":"preview-scripts/assets/scripts/Store/Store.js"},{"deps":{"../Manager/GameSaveManager":36,"../../core/mvc/BaseController":19},"path":"preview-scripts/assets/scripts/controllers/GameController.js"},{"deps":{"../../enums/PlantType":12,"../../enums/CattleType":18,"../../enums/YieldType":11,"../../enums/LandType":31,"../../enums/WorkerType":23,"../../enums/MachineType":1,"../../enums/Type":17,"../utils/CSVLoader":13},"path":"preview-scripts/assets/scripts/data/GameConfig.js"},{"deps":{"../../enums/PlantType":12,"../../enums/CattleType":18,"../Store/Store":5,"../data/GameConfig":7,"../storage/Storage":9,"../ui/LandUI":33,"../../core/mvc/BaseModel":20},"path":"preview-scripts/assets/scripts/models/GameModel.js"},{"deps":{"../ui/LandUI":33,"../Manager/UIManager":35},"path":"preview-scripts/assets/scripts/storage/Storage.js"},{"deps":{"../Manager/UIManager":35},"path":"preview-scripts/assets/scripts/ui/StorageUI.js"},{"deps":{},"path":"preview-scripts/assets/enums/YieldType.js"},{"deps":{},"path":"preview-scripts/assets/enums/PlantType.js"},{"deps":{},"path":"preview-scripts/assets/scripts/utils/CSVLoader.js"},{"deps":{"../../core/mvc/BaseView":2},"path":"preview-scripts/assets/scripts/views/GameView.js"},{"deps":{},"path":"preview-scripts/assets/interfaces/IStorage.js"},{"deps":{},"path":"preview-scripts/assets/interfaces/IStore.js"},{"deps":{},"path":"preview-scripts/assets/enums/Type.js"},{"deps":{},"path":"preview-scripts/assets/enums/CattleType.js"},{"deps":{},"path":"preview-scripts/assets/core/mvc/BaseController.js"},{"deps":{},"path":"preview-scripts/assets/core/mvc/BaseModel.js"},{"deps":{},"path":"preview-scripts/assets/interfaces/IAsset.js"},{"deps":{},"path":"preview-scripts/assets/interfaces/IMachine.js"},{"deps":{},"path":"preview-scripts/assets/enums/WorkerType.js"},{"deps":{},"path":"preview-scripts/assets/interfaces/IWorker.js"},{"deps":{},"path":"preview-scripts/assets/scripts/models/PlantModel.js"},{"deps":{},"path":"preview-scripts/assets/scripts/models/MachineModel.js"},{"deps":{},"path":"preview-scripts/assets/interfaces/IYield.js"},{"deps":{},"path":"preview-scripts/assets/scripts/models/CattleModel.js"},{"deps":{},"path":"preview-scripts/assets/scripts/models/WorkerModel.js"},{"deps":{},"path":"preview-scripts/assets/scripts/models/LandModel.js"},{"deps":{},"path":"preview-scripts/assets/enums/LandType.js"},{"deps":{},"path":"preview-scripts/assets/scripts/models/YieldModel.js"},{"deps":{"../../enums/PlantType":12,"../../enums/CattleType":18,"../Manager/UIManager":35,"../data/GameConfig":7},"path":"preview-scripts/assets/scripts/ui/LandUI.js"},{"deps":{"../Manager/UIManager":35},"path":"preview-scripts/assets/scripts/ui/StoreUI.js"},{"deps":{"./GameSaveManager":36,"../controllers/GameController":6,"../models/GameModel":8,"../ui/StorageUI":10,"../ui/StoreUI":34,"../ui/LandUI":33,"../views/GameView":14},"path":"preview-scripts/assets/scripts/Manager/UIManager.js"},{"deps":{},"path":"preview-scripts/assets/scripts/Manager/GameSaveManager.js"},{"deps":{"./Manager/UIManager":35},"path":"preview-scripts/assets/scripts/PanelUI.js"}];
var entries = ["preview-scripts/__qc_index__.js"];
var bundleScript = 'preview-scripts/__qc_bundle__.js';

/**
 * Notice: This file can not use ES6 (for IE 11)
 */
var modules = {};
var name2path = {};

// Will generated by module.js plugin
// var scripts = ${scripts};
// var entries = ${entries};
// var bundleScript = ${bundleScript};

if (typeof global === 'undefined') {
    window.global = window;
}

var isJSB = typeof jsb !== 'undefined';

function getXMLHttpRequest () {
    return window.XMLHttpRequest ? new window.XMLHttpRequest() : new ActiveXObject('MSXML2.XMLHTTP');
}

function downloadText(url, callback) {
    if (isJSB) {
        var result = jsb.fileUtils.getStringFromFile(url);
        callback(null, result);
        return;
    }

    var xhr = getXMLHttpRequest(),
        errInfo = 'Load text file failed: ' + url;
    xhr.open('GET', url, true);
    if (xhr.overrideMimeType) xhr.overrideMimeType('text\/plain; charset=utf-8');
    xhr.onload = function () {
        if (xhr.readyState === 4) {
            if (xhr.status === 200 || xhr.status === 0) {
                callback(null, xhr.responseText);
            }
            else {
                callback({status:xhr.status, errorMessage:errInfo + ', status: ' + xhr.status});
            }
        }
        else {
            callback({status:xhr.status, errorMessage:errInfo + '(wrong readyState)'});
        }
    };
    xhr.onerror = function(){
        callback({status:xhr.status, errorMessage:errInfo + '(error)'});
    };
    xhr.ontimeout = function(){
        callback({status:xhr.status, errorMessage:errInfo + '(time out)'});
    };
    xhr.send(null);
};

function loadScript (src, cb) {
    if (typeof require !== 'undefined') {
        require(src);
        return cb();
    }

    // var timer = 'load ' + src;
    // console.time(timer);

    var scriptElement = document.createElement('script');

    function done() {
        // console.timeEnd(timer);
        // deallocation immediate whatever
        scriptElement.remove();
    }

    scriptElement.onload = function () {
        done();
        cb();
    };
    scriptElement.onerror = function () {
        done();
        var error = 'Failed to load ' + src;
        console.error(error);
        cb(new Error(error));
    };
    scriptElement.setAttribute('type','text/javascript');
    scriptElement.setAttribute('charset', 'utf-8');
    scriptElement.setAttribute('src', src);

    document.head.appendChild(scriptElement);
}

function loadScripts (srcs, cb) {
    var n = srcs.length;

    srcs.forEach(function (src) {
        loadScript(src, function () {
            n--;
            if (n === 0) {
                cb();
            }
        });
    })
}

function formatPath (path) {
    let destPath = window.__quick_compile_project__.destPath;
    if (destPath) {
        let prefix = 'preview-scripts';
        if (destPath[destPath.length - 1] === '/') {
            prefix += '/';
        }
        path = path.replace(prefix, destPath);
    }
    return path;
}

window.__quick_compile_project__ = {
    destPath: '',

    registerModule: function (path, module) {
        path = formatPath(path);
        modules[path].module = module;
    },

    registerModuleFunc: function (path, func) {
        path = formatPath(path);
        modules[path].func = func;

        var sections = path.split('/');
        var name = sections[sections.length - 1];
        name = name.replace(/\.(?:js|ts|json)$/i, '');
        name2path[name] = path;
    },

    require: function (request, path) {
        var m, requestScript;

        path = formatPath(path);
        if (path) {
            m = modules[path];
            if (!m) {
                console.warn('Can not find module for path : ' + path);
                return null;
            }
        }

        if (m) {
            let depIndex = m.deps[request];
            // dependence script was excluded
            if (depIndex === -1) {
                return null;
            }
            else {
                requestScript = scripts[ m.deps[request] ];
            }
        }
        
        let requestPath = '';
        if (!requestScript) {
            // search from name2path when request is a dynamic module name
            if (/^[\w- .]*$/.test(request)) {
                requestPath = name2path[request];
            }

            if (!requestPath) {
                if (CC_JSB) {
                    return require(request);
                }
                else {
                    console.warn('Can not find deps [' + request + '] for path : ' + path);
                    return null;
                }
            }
        }
        else {
            requestPath = formatPath(requestScript.path);
        }

        let requestModule = modules[requestPath];
        if (!requestModule) {
            console.warn('Can not find request module for path : ' + requestPath);
            return null;
        }

        if (!requestModule.module && requestModule.func) {
            requestModule.func();
        }

        if (!requestModule.module) {
            console.warn('Can not find requestModule.module for path : ' + path);
            return null;
        }

        return requestModule.module.exports;
    },

    run: function () {
        entries.forEach(function (entry) {
            entry = formatPath(entry);
            var module = modules[entry];
            if (!module.module) {
                module.func();
            }
        });
    },

    load: function (cb) {
        var self = this;

        var srcs = scripts.map(function (script) {
            var path = formatPath(script.path);
            modules[path] = script;

            if (script.mtime) {
                path += ("?mtime=" + script.mtime);
            }
            return path;
        });

        console.time && console.time('load __quick_compile_project__');
        // jsb can not analysis sourcemap, so keep separate files.
        if (bundleScript && !isJSB) {
            downloadText(formatPath(bundleScript), function (err, bundleSource) {
                console.timeEnd && console.timeEnd('load __quick_compile_project__');
                if (err) {
                    console.error(err);
                    return;
                }

                let evalTime = 'eval __quick_compile_project__ : ' + srcs.length + ' files';
                console.time && console.time(evalTime);
                var sources = bundleSource.split('\n//------QC-SOURCE-SPLIT------\n');
                for (var i = 0; i < sources.length; i++) {
                    if (sources[i]) {
                        window.eval(sources[i]);
                        // not sure why new Function cannot set breakpoints precisely
                        // new Function(sources[i])()
                    }
                }
                self.run();
                console.timeEnd && console.timeEnd(evalTime);
                cb();
            })
        }
        else {
            loadScripts(srcs, function () {
                self.run();
                console.timeEnd && console.timeEnd('load __quick_compile_project__');
                cb();
            });
        }
    }
};

// Polyfill for IE 11
if (!('remove' in Element.prototype)) {
    Element.prototype.remove = function () {
        if (this.parentNode) {
            this.parentNode.removeChild(this);
        }
    };
}
})();
    